Repository MatthiWare/FinancialModelingPrep.NET, pull requests merged in 2025-02, with the labels that each got.

#140 added from, to and extended query params to GetHistoricalPricesForChartWithVolume
  FinancialModelingPrepApi/Abstractions/StockTimeSeries/IStockTimeSeriesProvider.cs
  FinancialModelingPrepApi/Core/StockTimeSeries/StockTimeSeriesProvider.cs
  Tests/StockTimeSeries/StockTimeSeriesTests.cs
Labels: enhancement, Breaking

#139 fix: volume average should be double
  FinancialModelingPrepApi/Model/CompanyValuation/CompanyProfileResponse.cs
Labels: bug, Breaking

#143 Prepare release `v0.4.0`
  FinancialModelingPrepApi/FinancialModelingPrepApi.csproj
  FinancialModelingPrepApi/FinancialModelingPrepApi.xml
Labels: documentation
